### PR TITLE
Simulation welded joints

### PR DESCRIPTION
**Pull request by AlexG1031**
Users can now create welded joints, which will allow users to create link shapes as they please.

### CODE REVIEW

**Comment by KohmeiK** [comment]
Really great work solving such a complex problem! 95% of the use cases are good now but I noticed a couple of issues:

One: Creating a tracer in the fillet section breaks a couple of things. I need to disable this in the context menu but you should probably block adding a tracer to the link without adding to a specific subset too.
One

Two: You can end up with compound link that is two separate links. When a connecting joint is deleted it should be converted to two links again.
Two

Three: This maybe out of scope since it deals with weird circular connections but this works when I don't set one of the joints as a ground and input which is weird.
Three

**Comment by KohmeiK** [comment]
I'm sorry you're probably sick of working on welded joints by now

**Comment by AlexG1031** [comment]
Hi Kohmei, 
These are great edge cases that you have found! I can figure out what is causing these bugs and fix it so we don't have these strange behaviors. 

1: Look later
2: Believe this is fixed now. 
3: Look into shortly

**Comment by AlexG1031** [comment]
I noticed that fixedLocations within the link's subset is not properly updated when we add a tracer point onto a link (I think we add the fixed point within the link itself and not the subset if this is the case condition). This will not be a problem within creating mechanisms but once we showcase FBDs and we do not see an option for attaching a certain joint as a fixed location. We can fix this problem once we showcase FBDs

**Comment by AlexG1031** [comment]
showcasing case 2:
showKohmei

**Review by KohmeiK — APPROVED** [review]
There are still bugs lefts (#170, and #171, probably a few more) but we're gonna call this good enough to merge.

**Pull request merged**
