### PR TITLE
Ansel forces

### LINKED ISSUE #48: Have force drag in a line when link is shaped as a binary
Image

If the user is dragging a force on a binary link, the force should snap onto the link. The user should not be allowed to drag the force off of the link but instead onto an imaginary line with the two joints as each line's endpoint. After reaching the joint, the user should also not be allowed to drag the force further. If the force contains more than two joints, this logic is not applicable anymore and the user will be able to drag however they want to.

To fix this bug, the user will have to dragForce method within grid-utils.service.ts file and adjust the logic to compensate for this. This method is called within new-grid.component.ts file under the mouseMove method.

### PR DESCRIPTION
**Pull request by AnselChang**
Fixes #48

After two really convoluted attempts, third solution is simply just finding the offset in which the joint moved, dividing it by the number of joints in the link, and offsetting the force vector by that amount.

### CODE REVIEW

**Comment by Kohmei358** [comment]
I feel like it's super close but not quite there. But maybe this is good enough? Will talk more during 7/3 meeting

**Comment by Kohmei358** [comment]
Wait for special case for binary links before merge

**Comment by KohmeiK** [comment]
Looks great! Need @AlexG1031 to merge with his PR.

**Comment by KohmeiK** [comment]
Merging with #123 since Alex pulled this code into his branch

**Pull request closed without merging**
