### PR TITLE
Force deletes when deleting a links

### PR DESCRIPTION
**Pull request by AlexG1031**
When a user deletes a link and the link has a force that is attached to a link, the force will also delete

### CODE REVIEW

**Comment by rkprad** [comment]
image
The above image works well. 
The below image also works
image

**Comment by rkprad** [comment]
Alex found the exact issue as to why deletion did not work well.

**Review by KohmeiK — CHANGES_REQUESTED** [review]
Jul-26-2023 21-06-26
Found a minor bug where forces don't get deleted when it's created before a link is welded.

**Comment by AlexG1031** [comment]
I am glad you found this bug Kohmei. Knowing the data structure, I know that force is stored within the subset and not within the link itself. If you tried to determine the analysis, there is strong chance that that force would not have been accounted for that link. 

So for this bug, when you weld a joint, we have to iterate through each subset and make sure that the force is added within the link. I can account for this most likely during this weekend.

**Review by KohmeiK — APPROVED** [review]

**Pull request merged**
