### PR TITLE
fixes #126 - adds "Send Project File" to help form

### LINKED ISSUE #126: Add 'Send a copy of the currently open mechanism' checkbox to the support email page

### PR DESCRIPTION
**Pull request by KohmeiK**

### CODE REVIEW

**Comment by KohmeiK** [comment]
All set!

**Comment by rkprad** [comment]
Looks good. Logo appears in Outlook but not in Gmail 
image

**Comment by KohmeiK** [comment]
That's an issue caused by the spam filter on your Gmail. Nothing we can do on our side, unfortunately.

**Review by AlexG1031 — APPROVED** [review]
lgtm

**Pull request merged**
