### PR TITLE
Undo/Redo, Save/Load

### PR DESCRIPTION
**Pull request by AnselChang**

### CODE REVIEW

**Comment by AlexG1031** [comment]
@AnselChang Very nice job within copy links and undo/redo.

**Comment by AlexG1031** [comment]
Very tiny thing, honestly insignficant, but just wanna document this:

UndoAnsel

Not sure how come but when I undo/redo adding a welded joint and an input joint, it combines these two as one step rather than two. 

Code currently looks good enough to me though to accept!

**Comment by AnselChang** [comment]
> Very tiny thing, honestly insignficant, but just wanna document this:
> 
> UndoAnsel
> 
> Not sure how come but when I undo/redo adding a welded joint and an input joint, it combines these two as one step rather than two.
> 
> Code currently looks good enough to me though to accept!

Fixed! Please let me know if you find other minor things like this, as I have to manually add save states for every important event.

**Comment by KohmeiK** [comment]
It looks like a lot of this works when using the context menu but not when using the edit panel. Can you double check? @AnselChang

**Comment by KohmeiK** [comment]
@AnselChang will take a look at updating the things that broke from the merge and will take a look at the panel linking issue

**Review by KohmeiK — APPROVED** [review]

**Pull request merged**
