### PR TITLE
Synthesis UI

### PR DESCRIPTION
**Pull request by AnselChang**

### CODE REVIEW

**Comment by KohmeiK** [comment]
@AnselChang made minor changes, please take a look and feel free to revert if you don't think it's the right choice

**Comment by AlexG1031** [comment]
lgtm! 

Be sure to document (create GitHub issue) that copying URL also copies that 3-pos synthesis.

Also, not sure if this will work for undo/redo section. If it doesn't, do make a GitHub issue for that!

**Review by AlexG1031 — APPROVED** [review]
lgtm!

**Comment by KohmeiK** [comment]
@AnselChang will do a final check then merge, approved by @KohmeiK and @AlexG1031, could possibly wait for @rkprad if he gets to this before Ansel

**Pull request merged**
