### PR TITLE
Change naming of input and ground label

### PR DESCRIPTION
**Pull request by AlexG1031**
Change ground and input label to "Ground Joint" and "Attach Input".

### CODE REVIEW

**Comment by rkprad** [comment]
Looks good.

**Review by rkprad — APPROVED** [review]
Looks good

**Comment by KohmeiK** [comment]
I wanted to change these labels last year but Prof Brown said that there was a lot of thought and deliberation about these names so we decided to keep it.

It was:
Add Ground <-> Remove Ground
Make Input <-> Remove Input

You changed it to: 
Ground Joint <-> Remove Ground
Attach Input <-> Remove Input

I think Ground Joint could be confusing since it's not clear if Ground is used an adjective or verb. (All other context menu items start with a verb.)
Also the symmetry of Add / Remove is gone. If we want "Ground Joint" it should probably be "Unground Joint"

Just some thoughts, I don't have a string preference for what we do though

**Comment by rkprad** [comment]
the pmksplus.mech.website has different labels compared to this new one. So, the option was either to go with what's available in the currently used version or have the new one but adjust it. That's why I adjusted them to be more appropriate from a kinematics and mechanisms perspective. 

For now, let the new change be as is. As I use this more, I'll see how this works and then decide.

**Pull request merged**
