### PR TITLE
Fixes #94 and #84. Redo SVGGrid to keep zoom level persistent on Resize fixing bugs and allowing smoother unit changes.

### LINKED ISSUE #94: First link becomes gigantic after window resize
1. Go to a blank open page
2. Resive the window
3. Create a new link
Image

This code is to blame: (src/app/component/new-grid/new-grid.component.ts line 530)
```
                if (this.mechanismSrv.links.length == 0) {
                  console.log('first link');
                  SettingsService._objectScale.next(
                    Number((70 / this.svgGrid.panZoomObject.getZoom()).toFixed(2))
                  );
                }
```

However, the root cause is that the zoom level of the svgGrid gets reset whenever the window is resized. 

 (src/app/component/new-grid/new-grid.component.ts line 95)
```
    fromEvent(window, 'resize')
      .pipe(debounceTime(200))
      .subscribe((event) => {
        console.log('resize');
        this.svgGrid.panZoomObject.resize();
        this.svgGrid.scaleToFitLinkage();
      });
```

### PR DESCRIPTION
**Pull request by KohmeiK**

### CODE REVIEW

**Comment by AlexG1031** [comment]
Hi @KohmeiK, nice job on fixing 94 and 84!

I found a bug that will require to take a look at. 

showKohmei

When you change to SI, for whatever reason, the ground joint disappears. When you change back to English and Metric, the ground joints appear again.

Also, I have a thought that I will want to ask about. In my mind, when the user inserts the joint values, they have a desired unit in mind but they do not know what the default global unit is. I suspect that students (novice users) will create a mechanism, go to settings, change the unit, and have to recreate the mechanism. With the way that this is set up, it implies that settings have to be done first, and then the mechanism will need to be created. However, users may not think in this order and they will want to create the mechanism first and then change the settings. In my mind, I think when the user changes the unit, neither the grid nor the mechanism should change. Curious to hear what you think.

**Comment by KohmeiK** [comment]
Oh I see where you're coming from. You're saying if a student never opens the edit panel, they won't notice the length units. Maybe the solution is to add a small unit indicator on the grid?

**Comment by KohmeiK** [comment]
Seems like anything less than object scale 0.5 breaks the SVG graphics on Chromium. How weird...

**Comment by AlexG1031** [comment]
One potential quick solution would be to not change the grid size. This may break other parts of code that showcases the scale but we can deal with these problems once we come across them...

**Review by AlexG1031 — APPROVED** [review]
lgtm, nice job!

**Pull request merged**
