### PR TITLE
Fixes #52, also visual graph fixes

### LINKED ISSUE #52: Analysis graphs tracers should be persistent when graphs are open (even if you switch active objects)
Whenever the user clicks on a different active object, the vertical tracer line (cursor) should be persistent when showing the current timestep and values. It should not go away when another object is clicked.

Image
The user drags the animation bar to a time to show the vertical cursor on the graph.

Image
If they click on the grid and click on the same object, the cursors disappear

Image
Same issue when they click on another object.

Currently, the only way to make the cursors show up is to slightly drag the animation bar again.

Relavant file:
src/app/component/analysis-graph/analysis-graph.component.ts

Line 358, check out these functions:

```        this.chart.clearAnnotations();
        this.chart.addXaxisAnnotation(
          {
            x: timeIndex,
            borderColor: '#313aa7',
            label: {
              text: 'T= ' + String((timeIndex / 62.5).toFixed(2)),
              orientation: 'horizontal',
              offsetY: -20,
            },
          },
          false
        );```

### PR DESCRIPTION
**Pull request by Kohmei358**
Let's see if adding everyone as reviews will get this reviewed quickly.

Resolved #52

### CODE REVIEW

**Comment by Kohmei358** [comment]
Typing in a time in the input box causes annotations to show undefined

**Comment by AlexG1031** [comment]
I believe what have done looks good to me. I found a bug with one of my test cases where velocity and acceleration do not show up...? I can add a bug issue in GitHub issue for someone to work on this issue. But believe what this GitHub issue calls for has been accounted for and works. 
 
image

**Review by AlexG1031 — APPROVED** [review]
Believe this works as intended.

**Comment by Kohmei358** [comment]
Yeah I believe the error you show here is unrelated to these changes. It will be good to investigate a bit more though

**Pull request merged**
