### PR TITLE
Closes #76, #41, #53

### LINKED ISSUE #76: Silder Angle Visual Bug
Image

The slider pill and the container rotate in opposite directions visually.

Issue probably in new-grid.html

### PR DESCRIPTION
**Pull request by Kohmei358**
Mostly fixing and moving labels and visual

### CODE REVIEW

**Comment by Kohmei358** [comment]
Screenshot 2023-05-29 at 6 53 00 PM

1 and 2a are now addressed
2b - Not a priority but added an issue: #83
3 - Need to discuss on Zoom or at a scrum. There are some benefits but I don't think there is a use-case for this.
4 - Created an issue: #84

**Comment by Kohmei358** [comment]
@AlexG1031 Review plz

**Comment by AlexG1031** [comment]
Looks good to me.

**Review by AlexG1031 — COMMENTED** [review]
Looks good to me.

**Review by AlexG1031 — APPROVED** [review]
Looks good to me.

**Pull request merged**
