### PR TITLE
closes #92 (Unit Testing)

### LINKED ISSUE #92: Position Analysis issues within PMKS+: Length of Links increasing and decreasing
This linkage [https://pmksplus.mech.website/?j=A,-3.74,-2.41,AB,R,t,0,0.1,t,%0AB,-2.72,0.91,AB%7CCBD,R,f,0,0.1,f,%0AC,1.58,0.43,CBD%7CCFG,R,f,0,0.1,f,%0AD,-0.24,4.01,DE%7CCBD,R,f,0,0.1,f,%0AE,5.08,5.31,DE%7CFE,R,f,0,0.1,f,%0AF,8.14,3.35,FE%7CCFG,R,f,0,0.1,f,%0AG,7.32,-3.51,CFG,R,t,0,0.1,f,%0A&l=AB,1,1,-3.2300000000000004,-0.75,A%7CB,,l,-2.72,-2.41,-3.74,-2.41,-3.74,0.91,-2.72,0.91%0ADE,1,1,2.42,4.659999999999999,D%7CE,,l,5.08,4.01,-0.24,4.01,-0.24,5.31,5.08,5.31%0ACBD,1,1,-0.3510600176910136,2.6313373415180026,B%7CC%7CD,,et,1.902,0.193,-3.086,0.75,-2.604,5.07,2.384,4.513%0AFE,1,1,6.609999999999999,4.33,E%7CF,,l,8.14,5.31,5.08,5.31,5.08,3.35,8.14,3.35%0ACFG,1,1,6.165062615799421,-1.0419214930288367,C%7CF%7CG,,et,1.182,0.472,8.375,3.674,11.148,-2.556,3.955,-5.757%0A&f=&pp=&tp=&s=10,false,false,cm](url) has increasing/decreasing link length and needs to be fixed.

### PR DESCRIPTION
**Pull request by JMRhodes03**
Test cases have been written and debugged, some cases are passing in the first rounds but failing as more time passes. the tolerance can be adjusted in the first section to change the tolerance for all tests.

### CODE REVIEW

**Review by AlexG1031 — APPROVED** [review]
lgtm!

**Comment by KohmeiK** [comment]
Screenshot 2023-08-23 at 9 37 34 PM

All of the positive tests are failing. Are you seeing something different? @JMRhodes03

**Comment by KohmeiK** [comment]
Also @JMRhodes03 Please pull from main into your branch so the merge is easier

**Comment by KohmeiK** [comment]
Also remove "With Invalid Data" since that doesn't make sense

**Review by AlexG1031 — APPROVED** [review]

**Review by AlexG1031 — CHANGES_REQUESTED** [review]
Just tested this within incognito mode and see that clicking on the URL for the MATLAB script sends me to a page that asks to log into WPI. Please update the URL so that it sends me directly to the MATLAB script.

**Review by AlexG1031 — APPROVED** [review]
lgtm!

**Pull request merged**
