### PR TITLE
104

### PR DESCRIPTION
**Pull request by KohmeiK**
I'm not gonna fix the input toggle since I'm goning to replace all of them with a 'Set as Input' button instead

### CODE REVIEW

**Comment by JMRhodes03** [comment]
https://photos.app.goo.gl/BCssgY5barWm7bai7 
found a bug:
when working with a slider that is horizontal from the adjacent grounded joint, trying to manipulate the input function of said slider faces many weird glitches, if using right click, it sets the adjacent grounded joint as input instead. and when using the edit menu once it is selected as input it cannot be unselected and the toggle remains in the negative positon.

**Comment by AlexG1031** [comment]
This is weird this error is here regarding setting an input joint to the slider-crank. I know that this error has been fixed before... Regardless, I'll find out why this is and adjust the logic accordingly.

**Comment by AlexG1031** [comment]
bugInputSlider
Found within link that mechanism positions cannot be found at certain joint positions. This will need to be examined further...

**Comment by AlexG1031** [comment]
There is another important thing we forgot to do. After adding the input joint onto a slider crank, we have to update the logic so that setting the input at the slider crank sets it as false.

**Comment by AlexG1031** [comment]
@Kohmei358 We have to update the context menu for when the user right clicks on the slider crank. When the user right-clicks, they are selecting the revolute joint. Users cannot select the prismatic joint. I think for this special case when the user selects the revJoint that is on top of the prismatic joint, we have to showcase the context menu for that joint rather than for the revolute joint. Let me know if this makes sense. I believe I will have to ask you for this part.

**Comment by AlexG1031** [comment]
I found a bug.
Create Link >> Add ground >> Add Input >> Add slider. Finish creating slider crank.
Mechanism positions are not found and somewhere the application produces an error.

**Review by AlexG1031 — APPROVED** [review]
lgtm!

**Pull request merged**
