### PR TITLE
Dragging a force on a binary link works properly now

### PR DESCRIPTION
**Pull request by AlexG1031**

### CODE REVIEW

**Comment by Kohmei358** [comment]
This might be related to #116 but when you drag a joint the force start point jumps.

Also, can you also get polygons working with just a simple edge snapping?

**Comment by AlexG1031** [comment]
I found the reason why the force jumps back to the original starting position. Need to spend more time on this bug but will fix this sometime this weekend.

**Comment by KohmeiK** [comment]
Really beautifully done! No is a valid answer here but can we add similar snapping on non-binary links, and also support similar constraints for welded binary links?

So force start points won't be able to leave a triangle link and it will want to snap to near the edge. Does that make sense?

**Comment by rkprad** [comment]
Issue found related to object scaling https://deploy-preview-123--pmks.netlify.app/?0P.1Ps.K,0.101.Ga,a,012e,0Op,0.Gb,b,9k,1Zi,0..YRab,ab,Fe,Fe,0ST,bT,c5cae9,a,b,,..2F1,ab,F1,2J,1Nb,0F5,0Vd,Fe.l 
image

**Review by KohmeiK — APPROVED** [review]
lgtm

**Pull request merged**
