### PR TITLE
Touchscreen

### LINKED ISSUE #50: The touchscreen warning shows up even when the users has touchscreen enabled laptop
Image

This warning should only show up on a touchscreen-only device like a tablet. Not a 2-in-1 laptop with a touch screen. Don't show this when the user device has a pointer. Also add a 'do not show again' check box.

Improve this funciton:
src/app/model/utils.ts (Line 1002)
```
export function is_touch_enabled() {
  return 'ontouchstart' in window || navigator.maxTouchPoints > 0;
}
```

There are different ways to implement a do not show again checkbox in your angular project. [One way is to use HTML5’s local storage to store the user’s preference and check it when the page is loaded](https://stackoverflow.com/questions/31842679/how-do-i-add-a-dont-show-this-message-again-checkbox-with-localstorage)[1](https://stackoverflow.com/questions/31842679/how-do-i-add-a-dont-show-this-message-again-checkbox-with-localstorage)

### PR DESCRIPTION
**Pull request by AnselChang**
fixes #50 

Need some testing to see whether the dismiss button actually works, and whether the modal only pops up when mouse does not exist. 

As mentioned in issue, I'm using code found here to detect a mouse
https://stackoverflow.com/questions/21054126/how-to-detect-if-a-device-has-mouse-support

unfortunately, it seems that it is far from perfect according to SO, ie Surface devices. It is hard to test on my end given I'm only using chrome debugger. it seems like more through testing on different devices is needed.

### CODE REVIEW

**Comment by Kohmei358** [comment]
@rkprad Please test this with your 2-1 laptop and make sure it popup doesn't show up at all if the device has a trackpad.
@AlexG1031 and @AnselChang please test with iPad to make sure it does show up and you can dismiss it forever

**Review by Kohmei358 — APPROVED** [review]

**Review by Kohmei358 — APPROVED** [review]
Looks good - Let's wait for Pradeep's review/testing until we merge

**Comment by AlexG1031** [comment]
> @rkprad Please test this with your 2-1 laptop and make sure it popup doesn't show up at all if the device has a trackpad.
> 
> @AlexG1031 and @JMRhodes03 please test with iPad to make sure it does show up and you can dismiss it forever

image

**Comment by rkprad** [comment]
Hi All, 

I checked with the 2-in-1 laptop and the error message does not show up. I tested on various browsers and things work as intended. 

I also tested on my android phone and tablet and things work as intended here as well (the don't show again button works as intended). 

Browsers Tested: Firefox, Chrome, Edge

**Pull request merged**
